<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salesactivity.proto

namespace SalesActivity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SalesActivity.SalesActivityActivationCompany</code>
 */
class SalesActivityActivationCompany extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string brand = 1;</code>
     */
    protected $brand = '';
    /**
     * Generated from protobuf field <code>string company = 2;</code>
     */
    protected $company = '';
    /**
     * Generated from protobuf field <code>string address = 3;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>string city = 4;</code>
     */
    protected $city = '';
    /**
     * Generated from protobuf field <code>string region = 5;</code>
     */
    protected $region = '';
    /**
     * Generated from protobuf field <code>string country = 6;</code>
     */
    protected $country = '';
    /**
     * Generated from protobuf field <code>string zipcode = 7;</code>
     */
    protected $zipcode = '';
    /**
     * Generated from protobuf field <code>string email = 8;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string phone = 9;</code>
     */
    protected $phone = '';
    /**
     * Generated from protobuf field <code>string fax = 10;</code>
     */
    protected $fax = '';
    /**
     * Generated from protobuf field <code>string website = 11;</code>
     */
    protected $website = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $brand
     *     @type string $company
     *     @type string $address
     *     @type string $city
     *     @type string $region
     *     @type string $country
     *     @type string $zipcode
     *     @type string $email
     *     @type string $phone
     *     @type string $fax
     *     @type string $website
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Salesactivity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string brand = 1;</code>
     * @return string
     */
    public function getBrand()
    {
        return $this->brand;
    }

    /**
     * Generated from protobuf field <code>string brand = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBrand($var)
    {
        GPBUtil::checkString($var, True);
        $this->brand = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string company = 2;</code>
     * @return string
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * Generated from protobuf field <code>string company = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCompany($var)
    {
        GPBUtil::checkString($var, True);
        $this->company = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 3;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string city = 4;</code>
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Generated from protobuf field <code>string city = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string region = 5;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Generated from protobuf field <code>string region = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string country = 6;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Generated from protobuf field <code>string country = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string zipcode = 7;</code>
     * @return string
     */
    public function getZipcode()
    {
        return $this->zipcode;
    }

    /**
     * Generated from protobuf field <code>string zipcode = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setZipcode($var)
    {
        GPBUtil::checkString($var, True);
        $this->zipcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 8;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string phone = 9;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Generated from protobuf field <code>string phone = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fax = 10;</code>
     * @return string
     */
    public function getFax()
    {
        return $this->fax;
    }

    /**
     * Generated from protobuf field <code>string fax = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setFax($var)
    {
        GPBUtil::checkString($var, True);
        $this->fax = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string website = 11;</code>
     * @return string
     */
    public function getWebsite()
    {
        return $this->website;
    }

    /**
     * Generated from protobuf field <code>string website = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setWebsite($var)
    {
        GPBUtil::checkString($var, True);
        $this->website = $var;

        return $this;
    }

}

