<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salesactivity.proto

namespace SalesActivity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SalesActivity.SalesActivityActivationCategory</code>
 */
class SalesActivityActivationCategory extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string roleid = 1;</code>
     */
    protected $roleid = '';
    /**
     * Generated from protobuf field <code>string categoryid = 2;</code>
     */
    protected $categoryid = '';
    /**
     * Generated from protobuf field <code>string subcategoryid = 3;</code>
     */
    protected $subcategoryid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $roleid
     *     @type string $categoryid
     *     @type string $subcategoryid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Salesactivity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string roleid = 1;</code>
     * @return string
     */
    public function getRoleid()
    {
        return $this->roleid;
    }

    /**
     * Generated from protobuf field <code>string roleid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleid($var)
    {
        GPBUtil::checkString($var, True);
        $this->roleid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string categoryid = 2;</code>
     * @return string
     */
    public function getCategoryid()
    {
        return $this->categoryid;
    }

    /**
     * Generated from protobuf field <code>string categoryid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryid($var)
    {
        GPBUtil::checkString($var, True);
        $this->categoryid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subcategoryid = 3;</code>
     * @return string
     */
    public function getSubcategoryid()
    {
        return $this->subcategoryid;
    }

    /**
     * Generated from protobuf field <code>string subcategoryid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSubcategoryid($var)
    {
        GPBUtil::checkString($var, True);
        $this->subcategoryid = $var;

        return $this;
    }

}

