<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salesactivity.proto

namespace SalesActivity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SalesActivity.SalesActivityUploadData</code>
 */
class SalesActivityUploadData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string memberid = 1;</code>
     */
    protected $memberid = '';
    /**
     * Generated from protobuf field <code>string base64 = 2;</code>
     */
    protected $base64 = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $memberid
     *     @type string $base64
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Salesactivity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string memberid = 1;</code>
     * @return string
     */
    public function getMemberid()
    {
        return $this->memberid;
    }

    /**
     * Generated from protobuf field <code>string memberid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMemberid($var)
    {
        GPBUtil::checkString($var, True);
        $this->memberid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string base64 = 2;</code>
     * @return string
     */
    public function getBase64()
    {
        return $this->base64;
    }

    /**
     * Generated from protobuf field <code>string base64 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBase64($var)
    {
        GPBUtil::checkString($var, True);
        $this->base64 = $var;

        return $this;
    }

}

