<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salesactivity.proto

namespace SalesActivity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SalesActivity.SalesActivityLoginList</code>
 */
class SalesActivityLoginList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string signature = 1;</code>
     */
    protected $signature = '';
    /**
     * Generated from protobuf field <code>string activityid = 2;</code>
     */
    protected $activityid = '';
    /**
     * Generated from protobuf field <code>string uniqueid = 3;</code>
     */
    protected $uniqueid = '';
    /**
     * Generated from protobuf field <code>string activityname = 4;</code>
     */
    protected $activityname = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $signature
     *     @type string $activityid
     *     @type string $uniqueid
     *     @type string $activityname
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Salesactivity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string signature = 1;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>string signature = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, True);
        $this->signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string activityid = 2;</code>
     * @return string
     */
    public function getActivityid()
    {
        return $this->activityid;
    }

    /**
     * Generated from protobuf field <code>string activityid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setActivityid($var)
    {
        GPBUtil::checkString($var, True);
        $this->activityid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uniqueid = 3;</code>
     * @return string
     */
    public function getUniqueid()
    {
        return $this->uniqueid;
    }

    /**
     * Generated from protobuf field <code>string uniqueid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUniqueid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uniqueid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string activityname = 4;</code>
     * @return string
     */
    public function getActivityname()
    {
        return $this->activityname;
    }

    /**
     * Generated from protobuf field <code>string activityname = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setActivityname($var)
    {
        GPBUtil::checkString($var, True);
        $this->activityname = $var;

        return $this;
    }

}

