<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salesactivity.proto

namespace SalesActivity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SalesActivity.SalesActivityConfirmationResponse</code>
 */
class SalesActivityConfirmationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string status = 1;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>repeated .SalesActivity.SalesActivityConfirmationProfile profile = 3;</code>
     */
    private $profile;
    /**
     * Generated from protobuf field <code>repeated .SalesActivity.SalesActivityConfirmationCategory category = 4;</code>
     */
    private $category;
    /**
     * Generated from protobuf field <code>repeated .SalesActivity.SalesActivityConfirmationCompany company = 5;</code>
     */
    private $company;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $status
     *     @type string $description
     *     @type array<\SalesActivity\SalesActivityConfirmationProfile>|\Google\Protobuf\Internal\RepeatedField $profile
     *     @type array<\SalesActivity\SalesActivityConfirmationCategory>|\Google\Protobuf\Internal\RepeatedField $category
     *     @type array<\SalesActivity\SalesActivityConfirmationCompany>|\Google\Protobuf\Internal\RepeatedField $company
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Salesactivity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string status = 1;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .SalesActivity.SalesActivityConfirmationProfile profile = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * Generated from protobuf field <code>repeated .SalesActivity.SalesActivityConfirmationProfile profile = 3;</code>
     * @param array<\SalesActivity\SalesActivityConfirmationProfile>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProfile($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SalesActivity\SalesActivityConfirmationProfile::class);
        $this->profile = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .SalesActivity.SalesActivityConfirmationCategory category = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Generated from protobuf field <code>repeated .SalesActivity.SalesActivityConfirmationCategory category = 4;</code>
     * @param array<\SalesActivity\SalesActivityConfirmationCategory>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCategory($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SalesActivity\SalesActivityConfirmationCategory::class);
        $this->category = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .SalesActivity.SalesActivityConfirmationCompany company = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * Generated from protobuf field <code>repeated .SalesActivity.SalesActivityConfirmationCompany company = 5;</code>
     * @param array<\SalesActivity\SalesActivityConfirmationCompany>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCompany($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SalesActivity\SalesActivityConfirmationCompany::class);
        $this->company = $arr;

        return $this;
    }

}

