<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salesactivity.proto

namespace SalesActivity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SalesActivity.SalesActivityUploadRequest</code>
 */
class SalesActivityUploadRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string signature = 1;</code>
     */
    protected $signature = '';
    /**
     * Generated from protobuf field <code>string remoteip = 2;</code>
     */
    protected $remoteip = '';
    /**
     * Generated from protobuf field <code>string langid = 3;</code>
     */
    protected $langid = '';
    /**
     * Generated from protobuf field <code>string weburl = 4;</code>
     */
    protected $weburl = '';
    /**
     * Generated from protobuf field <code>string activityid = 5;</code>
     */
    protected $activityid = '';
    /**
     * Generated from protobuf field <code>string uniqueid = 6;</code>
     */
    protected $uniqueid = '';
    /**
     * Generated from protobuf field <code>bool isdelete = 7;</code>
     */
    protected $isdelete = false;
    /**
     * Generated from protobuf field <code>repeated .SalesActivity.SalesActivityUploadData data = 8;</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $signature
     *     @type string $remoteip
     *     @type string $langid
     *     @type string $weburl
     *     @type string $activityid
     *     @type string $uniqueid
     *     @type bool $isdelete
     *     @type array<\SalesActivity\SalesActivityUploadData>|\Google\Protobuf\Internal\RepeatedField $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Salesactivity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string signature = 1;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>string signature = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, True);
        $this->signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string remoteip = 2;</code>
     * @return string
     */
    public function getRemoteip()
    {
        return $this->remoteip;
    }

    /**
     * Generated from protobuf field <code>string remoteip = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRemoteip($var)
    {
        GPBUtil::checkString($var, True);
        $this->remoteip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string langid = 3;</code>
     * @return string
     */
    public function getLangid()
    {
        return $this->langid;
    }

    /**
     * Generated from protobuf field <code>string langid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLangid($var)
    {
        GPBUtil::checkString($var, True);
        $this->langid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string weburl = 4;</code>
     * @return string
     */
    public function getWeburl()
    {
        return $this->weburl;
    }

    /**
     * Generated from protobuf field <code>string weburl = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setWeburl($var)
    {
        GPBUtil::checkString($var, True);
        $this->weburl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string activityid = 5;</code>
     * @return string
     */
    public function getActivityid()
    {
        return $this->activityid;
    }

    /**
     * Generated from protobuf field <code>string activityid = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setActivityid($var)
    {
        GPBUtil::checkString($var, True);
        $this->activityid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uniqueid = 6;</code>
     * @return string
     */
    public function getUniqueid()
    {
        return $this->uniqueid;
    }

    /**
     * Generated from protobuf field <code>string uniqueid = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUniqueid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uniqueid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isdelete = 7;</code>
     * @return bool
     */
    public function getIsdelete()
    {
        return $this->isdelete;
    }

    /**
     * Generated from protobuf field <code>bool isdelete = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsdelete($var)
    {
        GPBUtil::checkBool($var);
        $this->isdelete = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .SalesActivity.SalesActivityUploadData data = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>repeated .SalesActivity.SalesActivityUploadData data = 8;</code>
     * @param array<\SalesActivity\SalesActivityUploadData>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SalesActivity\SalesActivityUploadData::class);
        $this->data = $arr;

        return $this;
    }

}

