<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salesactivity.proto

namespace SalesActivity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SalesActivity.SalesActivityLoginList</code>
 */
class SalesActivityLoginList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string signature = 1;</code>
     */
    protected $signature = '';
    /**
     * Generated from protobuf field <code>string activityid = 2;</code>
     */
    protected $activityid = '';
    /**
     * Generated from protobuf field <code>string uniqueid = 3;</code>
     */
    protected $uniqueid = '';
    /**
     * Generated from protobuf field <code>string activityname = 4;</code>
     */
    protected $activityname = '';
    /**
     * Generated from protobuf field <code>string activitylocation = 5;</code>
     */
    protected $activitylocation = '';
    /**
     * Generated from protobuf field <code>string activitycity = 6;</code>
     */
    protected $activitycity = '';
    /**
     * Generated from protobuf field <code>string activitystart = 7;</code>
     */
    protected $activitystart = '';
    /**
     * Generated from protobuf field <code>string activityend = 8;</code>
     */
    protected $activityend = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $signature
     *     @type string $activityid
     *     @type string $uniqueid
     *     @type string $activityname
     *     @type string $activitylocation
     *     @type string $activitycity
     *     @type string $activitystart
     *     @type string $activityend
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Salesactivity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string signature = 1;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>string signature = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, True);
        $this->signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string activityid = 2;</code>
     * @return string
     */
    public function getActivityid()
    {
        return $this->activityid;
    }

    /**
     * Generated from protobuf field <code>string activityid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setActivityid($var)
    {
        GPBUtil::checkString($var, True);
        $this->activityid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uniqueid = 3;</code>
     * @return string
     */
    public function getUniqueid()
    {
        return $this->uniqueid;
    }

    /**
     * Generated from protobuf field <code>string uniqueid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUniqueid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uniqueid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string activityname = 4;</code>
     * @return string
     */
    public function getActivityname()
    {
        return $this->activityname;
    }

    /**
     * Generated from protobuf field <code>string activityname = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setActivityname($var)
    {
        GPBUtil::checkString($var, True);
        $this->activityname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string activitylocation = 5;</code>
     * @return string
     */
    public function getActivitylocation()
    {
        return $this->activitylocation;
    }

    /**
     * Generated from protobuf field <code>string activitylocation = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setActivitylocation($var)
    {
        GPBUtil::checkString($var, True);
        $this->activitylocation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string activitycity = 6;</code>
     * @return string
     */
    public function getActivitycity()
    {
        return $this->activitycity;
    }

    /**
     * Generated from protobuf field <code>string activitycity = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setActivitycity($var)
    {
        GPBUtil::checkString($var, True);
        $this->activitycity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string activitystart = 7;</code>
     * @return string
     */
    public function getActivitystart()
    {
        return $this->activitystart;
    }

    /**
     * Generated from protobuf field <code>string activitystart = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setActivitystart($var)
    {
        GPBUtil::checkString($var, True);
        $this->activitystart = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string activityend = 8;</code>
     * @return string
     */
    public function getActivityend()
    {
        return $this->activityend;
    }

    /**
     * Generated from protobuf field <code>string activityend = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setActivityend($var)
    {
        GPBUtil::checkString($var, True);
        $this->activityend = $var;

        return $this;
    }

}

