<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salesactivity.proto

namespace SalesActivity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SalesActivity.SalesActivityCategoryList</code>
 */
class SalesActivityCategoryList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string categoryid = 1;</code>
     */
    protected $categoryid = '';
    /**
     * Generated from protobuf field <code>string subcategoryid = 2;</code>
     */
    protected $subcategoryid = '';
    /**
     * Generated from protobuf field <code>string category = 3;</code>
     */
    protected $category = '';
    /**
     * Generated from protobuf field <code>string subcategory = 4;</code>
     */
    protected $subcategory = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $categoryid
     *     @type string $subcategoryid
     *     @type string $category
     *     @type string $subcategory
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Salesactivity::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string categoryid = 1;</code>
     * @return string
     */
    public function getCategoryid()
    {
        return $this->categoryid;
    }

    /**
     * Generated from protobuf field <code>string categoryid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCategoryid($var)
    {
        GPBUtil::checkString($var, True);
        $this->categoryid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subcategoryid = 2;</code>
     * @return string
     */
    public function getSubcategoryid()
    {
        return $this->subcategoryid;
    }

    /**
     * Generated from protobuf field <code>string subcategoryid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubcategoryid($var)
    {
        GPBUtil::checkString($var, True);
        $this->subcategoryid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category = 3;</code>
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Generated from protobuf field <code>string category = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subcategory = 4;</code>
     * @return string
     */
    public function getSubcategory()
    {
        return $this->subcategory;
    }

    /**
     * Generated from protobuf field <code>string subcategory = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSubcategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->subcategory = $var;

        return $this;
    }

}

